/** @type {import('tailwindcss').Config} */
import tailwindcssThemer from "tailwindcss-themer";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./ui/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        "2xs": "360px",
        xs: "480px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      fontSize: {
        "4xs": ["0.5625rem", "0.75rem"],
        "3xs": ["0.625rem", "0.8333rem"],
        "2xs": ["0.6875rem", "0.8594rem"],
      },
      borderWidth: {
        "1": "1px",
        "3": "3px",
        "5": "5px",
        "10": "10px",
      },
      background: {},
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "radial-custom-active":
          "radial-gradient(circle at 100% 0, rgba(204, 0, 0, 0) 0.9375rem, rgb(236, 242, 79) 0.9375rem)",
        "radial-custom":
          "radial-gradient(circle at 100% 0, rgba(204, 0, 0, 0) 0.9375rem, rgb(28, 37, 50) 0.9375rem)",
      },
      keyframes: {
        blink: {
          "0%, 50%, 100%": { transform: "scale(.9)" },
          "25%, 75%": { transform: "scale(1)" },
        },
        blink2: {
          "0%, 60%, 100%": { transform: "scale(.9)" },
          "20%": { transform: "scale(1)" },
        },
        VipCardWaterMarkfadeOut: {
          "0%": { opacity: "0.2" },
          "50%": { opacity: "0.8" },
          "100%": { opacity: "0.3" },
        },
        glassShiningEffect: {
          "0%, 45%, 65%, 90%, 100%": {
            opacity: "0",
            right: "-120px",
          },
          "50%, 95%": {
            opacity: "0",
            right: "350px",
          },
          "0%, 47.5%, 55%, 92.5%, 97.5%": {
            opacity: "1",
          },
        },
      },
      animation: {
        blink: "blink 1.5s ease 0s infinite normal none running",
        blink2: "blink2 2s ease 0s infinite normal none running",
        VipCardWaterMarkfadeOut:
          "VipCardWaterMarkfadeOut 1.5s ease-in-out alternate forwards",
        glassShiningEffect:
          "glassShiningEffect 15s ease-in-out infinite forwards",
      },
    },
  },
  plugins: [
    tailwindcssThemer({
      defaultTheme: {
        extend: {
          colors: {
            "base-black": "#000000",
            "base-white": "#ffffff",
            "base-100": "#a7b5ca",
            "base-200": "#93acd3",
            "base-300": "#6e81a0",
            "base-400": "#55657e",
            "base-500": "#3c485c",
            "base-600": "#2a3546",
            "base-700": "#263041",
            "base-800": "#202a39",
            "base-900": "#1c2532",
            "primary-default": "#2283f6",
            "primary-hover": "#0b6ada",
            "primary-active": "#075cc0",
            "primary-fore": "#ffffff",
            "info-default": "#2283f6",
            "info-hover": "#0b6ada",
            "info-active": "#075cc0",
            "info-fore": "#ffffff",
            "success-default": "#1bb83d",
            "success-hover": "#1ca63a",
            "success-active": "#1b9636",
            "success-fore": "#ffffff",
            "warning-default": "#ffb636",
            "warning-hover": "#ffa200",
            "warning-active": "#f09000",
            "warning-fore": "#ffffff",
            "error-default": "#ed1d49",
            "error-hover": "#c31d40",
            "error-active": "#ae1435",
            "error-fore": "#ffffff",
            "back-100": "#0d131c",
            "back-200": "#111923",
            "back-300": "#161f2c",
            "topapp-back": "#0d131c",
            "header-back": "#161f2c",
            "footer-back": "#161f2c",
            "tabbar-back": "#111923",
            "sidebar-back": "#161f2c",
          },
          fontFamily: {
            sans: ["Montserrat", "sans-serif"],
            serif: ["Merriweather", "serif"],
          },
        },
      },
      themes: [
        {
          name: "SnowWhite",
          selectors: ['[data-theme-color="SnowWhite"]'],
          extend: {
            colors: {
              "base-black": "#ffffff",
              "base-white": "#000000",
              "base-100": "#3F4F70",
              "base-200": "#606E8A",
              "base-300": "#758097",
              "base-400": "#959EB0",
              "base-500": "#B6BDC5",
              "base-600": "#D2D6DB",
              "base-700": "#E3E6EB",
              "base-800": "#EDEFF1",
              "base-900": "#F4F6F7",
              "primary-default": "#2283f6",
              "primary-hover": "#0b6ada",
              "primary-active": "#075cc0",
              "primary-fore": "#ffffff",
              "info-default": "#2283f6",
              "info-hover": "#0b6ada",
              "info-active": "#075cc0",
              "info-fore": "#ffffff",
              "success-default": "#1bb83d",
              "success-hover": "#1ca63a",
              "success-active": "#1b9636",
              "success-fore": "#ffffff",
              "warning-default": "#ffb636",
              "warning-hover": "#ffa200",
              "warning-active": "#f09000",
              "warning-fore": "#ffffff",
              "error-default": "#ed1d49",
              "error-hover": "#c31d40",
              "error-active": "#ae1435",
              "error-fore": "#ffffff",
              "back-100": "#f4f6f7",
              "back-200": "#e3e6eb",
              "back-300": "#ffffff",
              "topapp-back": "#390c0c",
              "header-back": "#ffffff",
              "footer-back": "#e3e6eb",
              "tabbar-back": "#ffffff",
              "sidebar-back": "#f4f6f7",
            },
            fontFamily: {
              sans: [
                "-apple-system",
                "BlinkMacSystemFont",
                "Helvetica Neue",
                "Helvetica",
                "Segoe UI",
                "Arial",
                "Roboto",
                "PingFang SC",
                "miui",
                "Hiragino Sans GB",
                "Microsoft Yahei",
                "sans-serif",
              ],
              serif: ["Merriweather", "serif"],
            },
          },
        },
        {
          name: "SaucePurple",
          selectors: ['[data-theme-color="SaucePurple"]'],
          extend: {
            colors: {
              "base-black": "#000000",
              "base-white": "#ffffff",
              "base-100": "#330215",
              "base-200": "#4c0113",
              "base-300": "#58071b",
              "base-400": "#651226",
              "base-500": "#701e31",
              "base-600": "#842239",
              "base-700": "#972e45",
              "base-800": "#b95b71",
              "base-900": "#d9859a",
              "primary-default": "#e9c86f",
              "primary-hover": "#dfbd63",
              "primary-active": "#bb993e",
              "primary-fore": "#4c0113",
              "info-default": "#1672f2",
              "info-hover": "#1678ff",
              "info-active": "#1678ff",
              "info-fore": "#ffffff",
              "success-default": "#04be02",
              "success-hover": "#18c516",
              "success-active": "#18c516",
              "success-fore": "#ffffff",
              "warning-default": "#ffaa09",
              "warning-hover": "#ffb325",
              "warning-active": "#ffb325",
              "warning-fore": "#ffffff",
              "error-default": "#ea4e3d",
              "error-hover": "#f35a4a",
              "error-active": "#f35a4a",
              "error-fore": "#ffffff",
              "back-100": "#330215",
              "back-200": "#4c0113",
              "back-300": "#58071b",
              "topapp-back": "#390c0c",
              "header-back": "#330215",
              "footer-back": "#330215",
              "tabbar-back": "#400114",
              "sidebar-back": "#4c0113",
            },
            fontFamily: {
              sans: [
                "-apple-system",
                "BlinkMacSystemFont",
                "Helvetica Neue",
                "Helvetica",
                "Segoe UI",
                "Arial",
                "Roboto",
                "PingFang SC",
                "miui",
                "Hiragino Sans GB",
                "Microsoft Yahei",
                "sans-serif",
              ],
              serif: ["Merriweather", "serif"],
            },
          },
        },
        {
          name: "SkyBlue",
          selectors: ['[data-theme-color="SkyBlue"]'],
          extend: {
            colors: {
              "base-black": "#000000",
              "base-white": "#ffffff",
              "base-100": "#006888",
              "base-200": "#007396",
              "base-300": "#0080A7",
              "base-400": "#0095C2",
              "base-500": "#02A9DD",
              "base-600": "#08C4FF",
              "base-700": "#00E3FF",
              "base-800": "#98EEFF",
              "base-900": "#D6FAFF",
              "primary-default": "#00E3FF",
              "primary-hover": "#08C4FF",
              "primary-active": "#02A9DD",
              "primary-fore": "#0080A7",
              "info-default": "#1672f2",
              "info-hover": "#1678ff",
              "info-active": "#1678ff",
              "info-fore": "#ffffff",
              "success-default": "#04be02",
              "success-hover": "#18c516",
              "success-active": "#18c516",
              "success-fore": "#ffffff",
              "warning-default": "#ffaa09",
              "warning-hover": "#ffb325",
              "warning-active": "#ffb325",
              "warning-fore": "#ffffff",
              "error-default": "#ea4e3d",
              "error-hover": "#f35a4a",
              "error-active": "#f35a4a",
              "error-fore": "#ffffff",
              "back-100": "#006888",
              "back-200": "#007396",
              "back-300": "#0080A7",
              "topapp-back": "#0DA3B5",
              "header-back": "#006888",
              "footer-back": "#006888",
              "tabbar-back": "#0080A7",
              "sidebar-back": "#02A9DD",
            },
            fontFamily: {
              sans: [
                "-apple-system",
                "BlinkMacSystemFont",
                "Helvetica Neue",
                "Helvetica",
                "Segoe UI",
                "Arial",
                "Roboto",
                "PingFang SC",
                "miui",
                "Hiragino Sans GB",
                "Microsoft Yahei",
                "sans-serif",
              ],
              serif: ["Merriweather", "serif"],
            },
          },
        },
      ],
    }),
  ],
};
